version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/app
    depends_on:
      - db

  db:
    container_name: 'database-node'
    image: mariadb:10.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sequre_db
